# Generated by Django 6.0.2 on 2026-02-26 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('common_error', models.TextField()),
                ('frequency', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='terraformrun',
            old_name='organization',
            new_name='org',
        ),
        migrations.RemoveField(
            model_name='infraresource',
            name='organization',
        ),
        migrations.AddField(
            model_name='infraresource',
            name='provider_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='infraresource',
            name='run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='api.terraformrun'),
        ),
        migrations.AddField(
            model_name='infraresource',
            name='status',
            field=models.CharField(default='Healthy', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='plan',
            field=models.CharField(default='Free', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='provider',
            field=models.CharField(default='GitHub', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='repo_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='terraformrun',
            name='plan_name',
            field=models.CharField(default='Default Plan', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terraformrun',
            name='provider',
            field=models.CharField(default='AWS', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terraformrun',
            name='version',
            field=models.CharField(default='1.0', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cifailure',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ci_failures', to='api.project'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='cloud_provider',
            field=models.CharField(default='aws', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='framework',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='CloudIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('account_id', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='CostRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('potential_savings', models.FloatField()),
                ('severity', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('engine', models.CharField(max_length=50)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('is_local', models.BooleanField(default=False)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='DiscoveredResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('resource_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('is_managed', models.BooleanField(default=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='GitIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='K8sCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=100)),
                ('nodes', models.IntegerField(default=0)),
                ('pods', models.IntegerField(default=0)),
                ('workload_count', models.IntegerField(default=0)),
                ('namespace_count', models.IntegerField(default=0)),
                ('cpu_usage', models.IntegerField(default=0)),
                ('mem_usage', models.IntegerField(default=0)),
                ('health_score', models.IntegerField(default=100)),
                ('status', models.CharField(max_length=50)),
                ('version', models.CharField(default='1.27', max_length=20)),
                ('provider', models.CharField(default='EKS', max_length=50)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_number', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=100)),
                ('triggered_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='Failure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(max_length=100)),
                ('error_message', models.TextField()),
                ('severity', models.CharField(max_length=20)),
                ('ai_explanation', models.TextField(blank=True)),
                ('suggested_fix', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failures', to='api.pipeline')),
            ],
        ),
    ]
