import React, { useState, useEffect } from 'react';
import {
    ArrowLeft, Activity, AlertTriangle, CheckCircle, ChevronRight,
    Code, GitBranch, RefreshCw, Layers, Play, Download, Copy,
    Zap, Server, Shield, Box
} from 'lucide-react';
import axios from 'axios';

const API = axios.create({ baseURL: 'http://localhost:8000/api' });

const StatusBadge = ({ status }) => {
    const map = {
        success: { color: '#00E676', bg: 'rgba(0,230,118,0.1)', label: 'Success' },
        failure: { color: '#FF3D00', bg: 'rgba(255,61,0,0.1)', label: 'Failed' },
        running: { color: '#FFB74D', bg: 'rgba(255,183,77,0.1)', label: 'Running' },
        pending: { color: '#4FC3F7', bg: 'rgba(79,195,247,0.1)', label: 'Pending' },
    };
    const s = map[status] || map.pending;
    return (
        <span style={{ padding: '4px 12px', borderRadius: '20px', fontSize: '12px', fontWeight: '700', background: s.bg, color: s.color, display: 'inline-flex', alignItems: 'center', gap: '6px' }}>
            <div style={{ width: '6px', height: '6px', borderRadius: '50%', background: s.color }} />
            {s.label}
        </span>
    );
};

const ProjectDetail = ({ projectId, onBack, onPipelineClick }) => {
    const [projectData, setProjectData] = useState(null);
    const [pipelines, setPipelines] = useState([]);
    const [loading, setLoading] = useState(true);
    const [isGenerating, setIsGenerating] = useState(false);
    const [selectedFile, setSelectedFile] = useState('Dockerfile');
    const [syncStatus, setSyncStatus] = useState('');
    const [copied, setCopied] = useState(false);

    const fetchProjectData = async () => {
        setLoading(true);
        try {
            const [projRes, pipeRes] = await Promise.all([
                API.get(`/projects/${projectId}/`),
                API.get('/pipelines/')
            ]);
            setProjectData(projRes.data);
            const allPipes = Array.isArray(pipeRes.data) ? pipeRes.data : (pipeRes.data?.data || []);
            setPipelines(allPipes.filter(p => p.project === projectId));
        } catch (err) {
            console.error('Error fetching project:', err);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => { fetchProjectData(); }, [projectId]);

    const handleGenerate = async () => {
        setIsGenerating(true);
        try {
            await API.post(`/projects/${projectId}/generate_devops/`);
            await fetchProjectData();
            alert('✅ DevOps configs regenerated by AI!');
        } catch {
            alert('Generation failed. Check backend.');
        } finally {
            setIsGenerating(false);
        }
    };

    const handleSyncGitHub = async () => {
        const repo = projectData?.repo_name || prompt('Enter GitHub repo (org/repo):', 'octocat/hello-world');
        if (!repo) return;
        setSyncStatus('Syncing GitHub...');
        try {
            const res = await API.post('/sync/github/', { repo_name: repo });
            setSyncStatus('✓ GitHub Synced');
            alert(`✅ GitHub Sync!\n${res.data?.message}\nRepos: ${(res.data?.synced_repos || [repo]).join(', ')}`);
            fetchProjectData();
        } catch {
            setSyncStatus('✗ Sync Failed');
            alert('GitHub sync failed.');
        }
    };

    const handleSyncJenkins = async () => {
        const job = prompt('Enter Jenkins job name:', projectData?.name || 'my-build');
        if (!job) return;
        setSyncStatus('Syncing Jenkins...');
        try {
            const res = await API.post('/sync/jenkins/', { job_name: job });
            const runs = res.data?.new_runs || [];
            setSyncStatus('✓ Jenkins Synced');
            alert(`✅ Jenkins Sync!\n${res.data?.message}\nNew runs: ${runs.length}`);
            fetchProjectData();
        } catch {
            setSyncStatus('✗ Sync Failed');
            alert('Jenkins sync failed.');
        }
    };

    const handleRunPipeline = async () => {
        try {
            await API.post(`/projects/${projectId}/deploy/`);
            alert('🚀 Pipeline triggered! Watch for new runs in the history below.');
            setTimeout(fetchProjectData, 2000);
        } catch {
            alert('Pipeline trigger failed.');
        }
    };

    const handleCopy = (text) => {
        navigator.clipboard.writeText(text).then(() => {
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        });
    };

    if (loading) return (
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '300px' }}>
            <div style={{ textAlign: 'center' }}>
                <RefreshCw size={32} color="var(--primary)" style={{ animation: 'spin 1s linear infinite', marginBottom: '16px' }} />
                <p style={{ color: 'var(--text-muted)' }}>Loading project intelligence...</p>
            </div>
        </div>
    );
    if (!projectData) return (
        <div style={{ textAlign: 'center', padding: '60px', color: 'var(--text-muted)' }}>
            <AlertTriangle size={40} style={{ marginBottom: '16px' }} />
            <p>Project not found.</p>
        </div>
    );

    const stats = {
        total: pipelines.length,
        success: pipelines.filter(p => p.status === 'success').length,
        failed: pipelines.filter(p => p.status === 'failure').length,
        rate: pipelines.length > 0 ? Math.round((pipelines.filter(p => p.status === 'success').length / pipelines.length) * 100) : 0,
    };

    const configMap = {
        Dockerfile: projectData.devops_config?.dockerfile,
        'K8s YAML': projectData.devops_config?.kubernetes_yaml,
        Terraform: projectData.devops_config?.terraform_config,
    };

    return (
        <div className="fade-in">
            <style>{`@keyframes spin { from { transform:rotate(0deg); } to { transform:rotate(360deg); } }`}</style>

            {/* Back Button */}
            <button onClick={onBack} style={{ display: 'flex', alignItems: 'center', gap: '8px', background: 'transparent', border: 'none', color: 'var(--primary)', cursor: 'pointer', marginBottom: '28px', fontSize: '14px', fontWeight: '600' }}>
                <ArrowLeft size={16} /> Back to Projects
            </button>

            {/* ── Project Header ── */}
            <div style={{ background: 'linear-gradient(135deg, rgba(255,61,0,0.08) 0%, rgba(0,0,0,0) 60%)', borderRadius: '24px', padding: '32px', border: '1px solid rgba(255,61,0,0.15)', marginBottom: '32px' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '16px' }}>
                    <div>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '14px', marginBottom: '10px' }}>
                            <div style={{ width: '52px', height: '52px', borderRadius: '14px', background: 'rgba(255,61,0,0.15)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                                <Layers size={28} color="var(--primary)" />
                            </div>
                            <div>
                                <h2 style={{ fontSize: '1.8rem', margin: 0 }}>{projectData.repo_name || projectData.name}</h2>
                                <p style={{ margin: '4px 0 0 0', color: 'var(--text-muted)', fontSize: '14px' }}>{projectData.description || 'BrainDevOps Integrated Repository'}</p>
                            </div>
                        </div>
                        <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap', marginTop: '12px' }}>
                            {[
                                { label: projectData.provider || 'GitHub', color: '#4FC3F7' },
                                { label: projectData.language || 'Node.js', color: '#00E676' },
                                { label: projectData.cloud_provider?.toUpperCase() || 'AWS', color: '#FF9800' },
                                { label: projectData.framework || 'Express', color: '#BB86FC' },
                            ].map((tag, i) => (
                                <span key={i} style={{ padding: '4px 12px', borderRadius: '12px', fontSize: '12px', fontWeight: '600', background: `${tag.color}15`, color: tag.color, border: `1px solid ${tag.color}30` }}>{tag.label}</span>
                            ))}
                            {syncStatus && <span style={{ padding: '4px 12px', borderRadius: '12px', fontSize: '12px', color: syncStatus.includes('✓') ? '#00E676' : '#FF3D00', background: 'rgba(0,0,0,0.2)' }}>{syncStatus}</span>}
                        </div>
                    </div>
                    <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap' }}>
                        <button className="btn-secondary" onClick={handleSyncGitHub} style={{ padding: '10px 18px', fontSize: '13px', display: 'flex', alignItems: 'center', gap: '8px', color: '#4FC3F7', borderColor: 'rgba(79,195,247,0.3)' }}>
                            <GitBranch size={16} /> Import GitHub
                        </button>
                        <button className="btn-secondary" onClick={handleSyncJenkins} style={{ padding: '10px 18px', fontSize: '13px', display: 'flex', alignItems: 'center', gap: '8px', color: '#ff6b6b', borderColor: 'rgba(255,61,0,0.3)' }}>
                            <RefreshCw size={16} /> Sync Jenkins
                        </button>
                        <button className="btn-primary" onClick={handleRunPipeline} style={{ padding: '10px 20px', fontSize: '13px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                            <Play size={16} /> Run Pipeline
                        </button>
                    </div>
                </div>
            </div>

            {/* ── Stats ── */}
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '20px', marginBottom: '32px' }}>
                {[
                    { label: 'TOTAL RUNS', value: stats.total, color: 'white', icon: <Activity size={20} /> },
                    { label: 'SUCCESS RATE', value: `${stats.rate}%`, color: '#00E676', icon: <CheckCircle size={20} /> },
                    { label: 'FAILED RUNS', value: stats.failed, color: '#FF3D00', icon: <AlertTriangle size={20} /> },
                    { label: 'AVG DURATION', value: '4m 12s', color: '#4FC3F7', icon: <Zap size={20} /> },
                ].map((s, i) => (
                    <div key={i} className="glass-card" style={{ padding: '24px' }}>
                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px' }}>
                            <p style={{ color: 'var(--text-muted)', fontSize: '11px', fontWeight: '600', textTransform: 'uppercase', letterSpacing: '0.08em', margin: 0 }}>{s.label}</p>
                            <div style={{ color: s.color, opacity: 0.7 }}>{s.icon}</div>
                        </div>
                        <h3 style={{ margin: 0, fontSize: '28px', fontWeight: '800', color: s.color }}>{s.value}</h3>
                    </div>
                ))}
            </div>

            {/* ── DevOps Config + Pipeline History ── */}
            <div style={{ display: 'grid', gridTemplateColumns: '1.2fr 1fr', gap: '24px', marginBottom: '32px' }}>
                {/* AI Config Viewer */}
                <div className="glass-card" style={{ padding: '28px' }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' }}>
                        <h4 style={{ margin: 0, display: 'flex', alignItems: 'center', gap: '10px' }}>
                            <Code size={18} color="var(--primary)" /> AI-Generated DevOps Config
                        </h4>
                        <button className="btn-primary" onClick={handleGenerate} disabled={isGenerating} style={{ padding: '8px 18px', fontSize: '13px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                            <RefreshCw size={14} style={{ animation: isGenerating ? 'spin 1s linear infinite' : 'none' }} />
                            {isGenerating ? 'Generating...' : 'Regenerate'}
                        </button>
                    </div>

                    {/* Tab Switcher */}
                    <div style={{ display: 'flex', gap: '6px', marginBottom: '16px', background: 'rgba(0,0,0,0.2)', borderRadius: '10px', padding: '4px' }}>
                        {Object.keys(configMap).map(file => (
                            <button key={file} onClick={() => setSelectedFile(file)} style={{
                                flex: 1, padding: '8px', borderRadius: '8px', border: 'none', cursor: 'pointer', fontSize: '12px', fontWeight: '600', transition: 'all 0.2s',
                                background: selectedFile === file ? 'rgba(255,61,0,0.2)' : 'transparent',
                                color: selectedFile === file ? 'var(--primary)' : 'var(--text-muted)',
                            }}>
                                {file === 'Dockerfile' ? '🐳' : file === 'K8s YAML' ? '☸️' : '🏗️'} {file}
                            </button>
                        ))}
                    </div>

                    {/* Code Block */}
                    <div style={{ position: 'relative' }}>
                        <button onClick={() => handleCopy(configMap[selectedFile] || '')} style={{
                            position: 'absolute', top: '10px', right: '10px', background: 'rgba(255,255,255,0.1)', border: '1px solid var(--glass-border)', color: copied ? '#00E676' : 'var(--text-muted)', borderRadius: '6px', padding: '4px 10px', fontSize: '11px', cursor: 'pointer', zIndex: 1, display: 'flex', alignItems: 'center', gap: '4px'
                        }}>
                            <Copy size={12} /> {copied ? 'Copied!' : 'Copy'}
                        </button>
                        <pre style={{
                            background: '#080810',
                            border: '1px solid var(--glass-border)',
                            borderRadius: '12px',
                            padding: '20px',
                            fontSize: '12px',
                            fontFamily: '"Fira Code", monospace',
                            color: configMap[selectedFile] ? '#a8d8a8' : 'var(--text-muted)',
                            overflowX: 'auto',
                            minHeight: '240px',
                            maxHeight: '320px',
                            overflowY: 'auto',
                            margin: 0,
                            lineHeight: '1.6',
                            whiteSpace: 'pre-wrap',
                            wordBreak: 'break-word'
                        }}>
                            {configMap[selectedFile] || `# No ${selectedFile} generated yet.\n# Click "Regenerate" to create AI-powered config\n# for ${projectData.language} / ${projectData.framework} on ${projectData.cloud_provider?.toUpperCase() || 'AWS'}.`}
                        </pre>
                    </div>
                </div>

                {/* Pipeline History */}
                <div className="glass-card" style={{ padding: '28px' }}>
                    <h4 style={{ marginBottom: '20px', display: 'flex', alignItems: 'center', gap: '10px' }}>
                        <Activity size={18} color="var(--secondary)" /> Pipeline History
                    </h4>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '10px', maxHeight: '420px', overflowY: 'auto' }}>
                        {pipelines.length > 0 ? pipelines.map((run) => (
                            <div key={run.id} onClick={() => onPipelineClick && onPipelineClick(run.id)} style={{
                                display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                                padding: '14px 16px', background: 'rgba(255,255,255,0.02)', borderRadius: '12px',
                                border: '1px solid rgba(255,255,255,0.05)', cursor: 'pointer', transition: 'all 0.2s'
                            }}
                                onMouseEnter={e => e.currentTarget.style.background = 'rgba(255,255,255,0.05)'}
                                onMouseLeave={e => e.currentTarget.style.background = 'rgba(255,255,255,0.02)'}
                            >
                                <div style={{ display: 'flex', alignItems: 'center', gap: '14px' }}>
                                    <div style={{
                                        width: '36px', height: '36px', borderRadius: '50%',
                                        background: run.status === 'success' ? 'rgba(0,230,118,0.1)' : 'rgba(255,61,0,0.1)',
                                        display: 'flex', alignItems: 'center', justifyContent: 'center',
                                        color: run.status === 'success' ? '#00E676' : 'var(--primary)'
                                    }}>
                                        {run.status === 'success' ? <CheckCircle size={18} /> : <AlertTriangle size={18} />}
                                    </div>
                                    <div>
                                        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '4px' }}>
                                            <span style={{ fontWeight: '700', fontSize: '14px' }}>#{run.build_number}</span>
                                            <StatusBadge status={run.status} />
                                        </div>
                                        <p style={{ margin: 0, fontSize: '11px', color: 'var(--text-muted)' }}>
                                            {run.branch || 'main'} • {run.triggered_by || 'System'} • {new Date(run.created_at).toLocaleDateString()}
                                        </p>
                                    </div>
                                </div>
                                <ChevronRight size={18} color="var(--text-muted)" />
                            </div>
                        )) : (
                            <div style={{ textAlign: 'center', padding: '40px 20px', color: 'var(--text-muted)' }}>
                                <GitBranch size={32} style={{ opacity: 0.4, marginBottom: '12px' }} />
                                <p style={{ margin: 0, fontSize: '14px' }}>No pipeline runs yet.</p>
                                <p style={{ margin: '8px 0 0 0', fontSize: '12px' }}>Click "Sync Jenkins" or "Import GitHub" to populate pipeline history.</p>
                            </div>
                        )}
                    </div>
                </div>
            </div>

            {/* ── DevOps Roles + Folder Map ── */}
            <div className="glass-card" style={{ padding: '28px' }}>
                <h4 style={{ marginBottom: '24px', display: 'flex', alignItems: 'center', gap: '10px' }}>
                    <Server size={18} color="var(--primary)" /> Project DevOps Architecture
                </h4>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '32px' }}>
                    {/* Role Mapping */}
                    <div>
                        <p style={{ margin: '0 0 16px 0', fontSize: '12px', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.1em' }}>Role Mapping</p>
                        <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
                            {[
                                { role: 'Infrastructure Engineer', tools: 'Terraform + AWS', desc: 'IaC in terraform/ folder manages VPC, EKS, S3.', color: '#FF3D00' },
                                { role: 'CI/CD Engineer', tools: 'GitHub + Jenkins', desc: 'Pipelines sync via GitHub webhook or Jenkins job.', color: '#4FC3F7' },
                                { role: 'SRE', tools: 'Kubernetes + Prometheus', desc: 'K8s clusters run backend/frontend containers.', color: '#00E676' },
                            ].map((m, i) => (
                                <div key={i} style={{ padding: '16px', background: 'rgba(255,255,255,0.02)', borderRadius: '12px', borderLeft: `3px solid ${m.color}` }}>
                                    <p style={{ margin: '0 0 2px 0', fontSize: '11px', color: m.color, fontWeight: '700', textTransform: 'uppercase' }}>{m.role}</p>
                                    <p style={{ margin: '0 0 6px 0', fontSize: '14px', fontWeight: '600' }}>{m.tools}</p>
                                    <p style={{ margin: 0, fontSize: '12px', color: 'var(--text-muted)' }}>{m.desc}</p>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* Folder Structure */}
                    <div>
                        <p style={{ margin: '0 0 16px 0', fontSize: '12px', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.1em' }}>Repository Structure</p>
                        <div style={{ background: '#080810', borderRadius: '14px', padding: '20px', border: '1px solid var(--glass-border)' }}>
                            <pre style={{ margin: 0, fontSize: '13px', color: '#4FC3F7', fontFamily: 'monospace', lineHeight: '2' }}>
                                {`📁 devops/
├── 🐍 backend/        ← Django API
│   ├── api/           ← Views, models
│   └── core/          ← Settings, URLs
├── ⚛️  my-devops/     ← React Frontend
│   └── src/
│       ├── components/← All tabs/pages
│       └── api/       ← API clients
├── 🏗️  terraform/     ← Infrastructure
│   ├── main.tf        ← VPC, EKS, S3
│   ├── variables.tf   ← Config vars
│   └── outputs.tf     ← Resource IDs
└── 🔄 .github/
    └── workflows/     ← CI/CD pipelines`}
                            </pre>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default ProjectDetail;
